CREATE DATABASE IF NOT EXISTS todos;
USE todo;
INSERT INTO todos VALUES(NULL, 1, 1, "Add more task");
INSERT INTO todos VALUES(NULL, 0, 1, "write codes");
INSERT INTO todos VALUES(NULL, 1, 0, "cook something nice");
INSERT INTO todos VALUES(NULL, 0, 0, "clean the kitchen");
INSERT INTO todos VALUES(NULL, 1, 1, "eat breakfast");
DESCRIBE todos;
SHOW TABLES;
SELECT * FROM todos;