SHOW DATABASES;
CREATE DATABASE IF NOT EXISTS todo_app;
USE todo_app;
CREATE TABLE todo_app(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
is_done BIT,
description VARCHAR (100)
);
INSERT INTO todo_app VALUES(NULL, 1, "SOLVE TODO-APP TASK");
INSERT INTO todo_app VALUES(NULL, 1, "CHECK IF IT IS WORKING");
INSERT INTO todo_app VALUES(NULL, 1, "IF YES BE HAPPY");
INSERT INTO todo_app VALUES(NULL, 0, "IF NOT TO SOLVE THE PROBLEM");
SHOW TABLES;
DESCRIBE todo_app;
SELECT * FROM todo_app; 




